### ISSUE TITLE
small bug with proxy address

### ISSUE THREAD

**Issue by sindizzy** [franzalex/ProxyManager#1]
Great work on this project. Just what i needed.
I found one small bug when my proxy is set as "http://prx1.corp.company.com:9000".
looks like you are splitting by : to get the port number. But the : in "http:" hoses that.

Exception thrown: 'System.FormatException' in mscorlib.dll
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt32(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.UInt16.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToUInt16(String value)
   at ProxyManager.ProxyAddress..ctor(String proxyAddress) in ProxyAddress.cs:line 45

**Comment by franzalex** [comment]
@sindizzy 
Good catch! 👍🏾 

This has been fixed and is live in the [latest release](/franzalex/ProxyManager/releases/tag/v0.10.20301.0340).
